name: audiobook_player
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  file_picker: ^10.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  just_audio: ^0.9.46
  path: ^1.9.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
